-- Enable Full Text Search (if looking for advanced configs, but simple text search is native)
-- We will use 'tsvector' for search.

-- Files Table
CREATE TABLE IF NOT EXISTS files (
    id text PRIMARY KEY,
    name text NOT NULL,
    size bigint NOT NULL,
    type text,
    iv text NOT NULL,
    salt text NOT NULL,
    status text DEFAULT 'pending',
    created_at timestamptz DEFAULT now(),
    search_vector tsvector
);

-- Index for searching
CREATE INDEX IF NOT EXISTS files_search_vector_idx ON files USING GIN(search_vector);
CREATE INDEX IF NOT EXISTS files_status_idx ON files(status);

-- Chunks Table
CREATE TABLE IF NOT EXISTS chunks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id text REFERENCES files(id) ON DELETE CASCADE,
    idx integer NOT NULL,
    message_id text NOT NULL,
    channel_id text NOT NULL,
    size integer NOT NULL,
    url text
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS chunks_file_id_idx ON chunks(file_id);
CREATE INDEX IF NOT EXISTS chunks_file_id_idx_idx ON chunks(file_id, idx);

-- Function to update search_vector automatically
create or replace function files_search_vector_update() returns trigger as $$
begin
    new.search_vector := to_tsvector('english', new.name);
    return new;
end
$$ language plpgsql;

-- Trigger to call the function
create or replace trigger files_search_vector_trigger
before insert or update on files
for each row execute function files_search_vector_update();

-- RPC for statistics (used in system.ts)
create or replace function get_total_size()
returns bigint
language sql
security definer
as $$
  select sum(size)::bigint from files where status = 'active';
$$;

-- RPC to get the database size in bytes
create or replace function get_db_size()
returns bigint
language sql
security definer
as $$
  select pg_database_size(current_database());
$$;
